// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdelwhvrcqsyxnydjmue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZWx3aHZyY3FzeXhueWRqbXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzgzODgsImV4cCI6MjA2NDYxNDM4OH0.skMBECdkzCs8yC7Y0lHhL3qxm66UEvB8ydP3-e8tPfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);